name: 'Hello World'
description: 'dummy-action'
inputs:
  my-input:  # id of input
    required: true
  my-other-input:
    required: false
  params:
    required: false


runs:
  using: 'node20'
  main: 'index.js'