on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          my-input: 'my world'
        env:
          My_env: "mixed case"
          MY_ENV: "all uppercasde"
          my_env: "all lowercase"
          Mixed_case: "hello"
          UPPER_CASE: "hello"
          lower_case: "hello"